version: '3.8'

services:
  subscriber:
    container_name: nk2-msp-subscriber-postver
    image: post:1.1v
    restart: always
    environment:
      MQTT_SUB_HOST: ${MQTT_SUB_HOST}
      MQTT_SUB_PORT: ${MQTT_SUB_PORT}
      MQTT_SUB_TOPIC: ${MQTT_SUB_TOPIC}
      TABLE_NAME: ${TABLE_NAME}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
