services:
  subscriber:
    container_name: nk3-post-test
    image: mochigome/post:2.3v.ecs
    restart: always
    env_file:
      - .env
    environment:
      MQTT_SUB_HOST: ${MQTT_SUB_HOST}
      MQTT_SUB_PORT: ${MQTT_SUB_PORT}
      MQTT_SUB_TOPIC: ${MQTT_SUB_TOPIC}
      TABLE_NAME: ${TABLE_NAME}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      POST_INTERVAL: ${POST_INTERVAL}
      KEY_OPTION: ${KEY_OPTION}
      ECS_MQTT_PRIVATE_KEY: ${ECS_MQTT_PRIVATE_KEY}
      ECS_MQTT_CLIENT_CERTIFICATE: ${ECS_MQTT_CLIENT_CERTIFICATE}
      ECS_MQTT_CA_CERTIFICATE: ${ECS_MQTT_CA_CERTIFICATE}
